### ISSUE TITLE
some bash scripts not marked +x

### ISSUE THREAD

**Issue by NickP1** [titancoinproject/Titan#8]
### Describe the issue
The build scripts fail for the raspberry Pi install method because the the autogen.sh and share/genbuild.sh files are not marked as executable.
### Can you reliably reproduce the issue?
Yes. 
#### If so, please list the steps to reproduce below:
1. On a Raspberry Pi running Raspbian 10 (buster)
2. git clone this repository
3. cd Titan and run:
./autogen.sh
./configure --disable-tests --with-gui=no CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib"
make

### Expected behaviour
autogen.sh should execute and after ./configure the make should execute then genbuild.sh

### Actual behaviour
autogen.sh "permission denied" because not executable. After chmod +x autogen.sh it will run.
After make when trying to run genbuild.sh "permission denied" again as not marked executable.

### Screenshots.
None

### What version of bitcoin-core are you using?
self compiled form this source

### Machine specs:
- OS: Raaspberry Pi 4B
- CPU: Model name:  Cortex-A72
- RAM: 4 GB
- Disk size: 32 GB
- Disk Type (HD/SDD): SDCARD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by titancoinproject** [comment]
Thank you for pointing out the issue. The build file has been updated. We really appreciate your help.
